version: "3.9"
services:
  frontend:
    image: ghcr.io/alduino/cab432-a1/frontend:latest
    environment:
      PORT: 80
  backend:
    image: ghcr.io/alduino/cab432-a1/backend:latest
    environment:
      PORT: 80
      TWITTER_API_KEY: "XXXX"
      TWITTER_API_SECRET: "XXXX"
      TWITCH_API_KEY: "XXXX"
      TWITCH_API_SECRET: "XXXX"
      TWITTER_BASE_USER: "309366491"
      YOUTUBE_API_KEY: "XXXX"
      DEBUG: "app:*,api:*"
  proxy:
    image: nginx:alpine
    restart: on-failure
    volumes:
      - ./prod-nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "${PORT}:80"
